# Generated by Django 5.1.4 on 2026-05-22 18:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_alter_gig_options_and_more'),
        ('payments', '0002_modernize_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_7a85fd_idx',
            old_name='pay_pay_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='pay_pay_status_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gig',
            field=models.ForeignKey(blank=True, help_text='Associated gig (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gigs.gig'),
        ),
    ]
