# Generated by Django 4.2.21 on 2025-06-10 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("employer", "Employer"),
                            ("freelancer", "Freelancer"),
                        ],
                        default="freelancer",
                        max_length=20,
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Tell us about yourself"),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated skills (e.g., Python, Django, JavaScript)",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Your hourly rate in USD (for freelancers)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Company name (for employers)",
                        max_length=100,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
