# Generated by Django 4.2.23 on 2025-10-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your hourly rate in GBP', max_digits=6, null=True),
        ),
    ]
