# Generated by Django 4.2.7 on 2025-06-08 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'due_date', 'created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget in USD', max_digits=8)),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('design', 'Design & Graphics'), ('writing', 'Writing & Content'), ('marketing', 'Marketing & Social Media'), ('data_entry', 'Data Entry'), ('admin', 'Administrative'), ('tech_support', 'Tech Support'), ('other', 'Other')], default='other', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured gigs appear at the top')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig',
                'verbose_name_plural': 'Gigs',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
