# Generated by Django 4.2.21 on 2025-06-29 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0003_delete_task_gig_updated_at_alter_gig_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('design', 'Graphic Design'), ('writing', 'Content Writing'), ('marketing', 'Digital Marketing'), ('data_entry', 'Data Entry'), ('translation', 'Translation'), ('video_editing', 'Video Editing'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text="Explain why you're the right fit for this gig")),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Your proposed rate for this project (optional)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_notes', models.TextField(blank=True, help_text='Internal notes from employer')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gigs.gig')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('gig', 'applicant')},
            },
        ),
    ]
