# Generated by Django 4.2.23 on 2025-10-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_alter_gig_budget_alter_gig_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['employer', '-created_at'], name='gigs_gig_employe_460f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['is_active', 'is_featured'], name='gigs_gig_is_acti_b44795_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['category'], name='gigs_gig_categor_5e4b01_idx'),
        ),
    ]
