# Generated by Django 5.1.4 on 2026-05-22 18:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_modernize_gig_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='gigs_applic_applica_6cd08f_idx',
            old_name='apps_appl_applicant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='gigs_applic_gig_id_067a79_idx',
            old_name='apps_appl_gig_status_idx',
        ),
        migrations.RenameIndex(
            model_name='gig',
            new_name='gigs_gig_slug_6216be_idx',
            old_name='gigs_gig_slug_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(help_text="Explain why you're the right fit for this gig."),
        ),
        migrations.AlterField(
            model_name='application',
            name='employer_notes',
            field=models.TextField(blank=True, help_text='Private notes visible only to the employer.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='proposed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your proposed rate for this project (optional).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='gig',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Total project budget in GBP.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.CharField(help_text="Where the work happens — 'Remote', a city, or a country.", max_length=100),
        ),
    ]
