#!/usr/bin/env bash
#
# Remove legacy files from the pre-overhaul project.
#
# This deletes:
#   * committed virtual environments (.venv, venv_local) — should never have
#     been committed in the first place
#   * the pre-built staticfiles/ collection (regenerated on demand)
#   * the bloated documentation files (122 KB README, 335 KB design.md, etc.)
#   * the docs/screenshots/ tree (the old screenshots reference the previous
#     UI and are no longer accurate)
#   * leftover Task-app templates and CSS that have been emptied out but still
#     exist on disk
#   * the obsolete app.py WSGI hack, the broken .env, Procfile, etc.
#
# Run this once from the project root, then commit the result.
#
# Usage:
#   bash scripts/cleanup-legacy.sh
#
# Dry-run first if you want to see what'd happen:
#   DRY_RUN=1 bash scripts/cleanup-legacy.sh

set -euo pipefail

DRY_RUN=${DRY_RUN:-0}

remove() {
  for path in "$@"; do
    if [ -e "$path" ] || [ -L "$path" ]; then
      if [ "$DRY_RUN" = "1" ]; then
        echo "would remove  $path"
      else
        echo "removing      $path"
        rm -rf "$path"
      fi
    fi
  done
}

# Committed virtual envs.
remove .venv venv_local venv

# Collected static files (regenerated by `manage.py collectstatic`).
remove staticfiles

# Legacy deployment cruft.
remove app.py Procfile .python-version .prettierignore .gitattributes

# The leaked .env (.env.example holds the new template).
remove .env

# Bloated documentation files — superseded by the new README.md.
remove README.md.legacy design.md code_quality.md testing.md \
       TESTING_MANUAL.md TESTING_METHODOLOGY.md TEST_EXECUTION_GUIDE.md

# Old screenshots referencing the previous UI.
remove docs/screenshots docs/design_patterns_examples.py

# Empty docs/ folder if nothing left in it.
if [ -d docs ] && [ -z "$(ls -A docs 2>/dev/null)" ]; then
  remove docs
fi

# Leftover Task-app templates (the project began life as a todo).
remove gigs/templates/gigs/task_list.html \
       gigs/templates/gigs/task_form.html \
       gigs/templates/gigs/task_detail.html \
       gigs/templates/gigs/task_confirm_delete.html

# Orphan todo_app static dir.
remove gigs/static/todo_app

# Duplicate registration login template (we use accounts/login.html).
remove gigs/templates/registration/login.html
[ -d gigs/templates/registration ] && rmdir gigs/templates/registration 2>/dev/null || true

# Old bespoke CSS — replaced by Tailwind utilities in the templates.
remove static/css/base.css \
       static/css/components.css \
       static/css/gigs.css \
       static/css/organized-styles.css \
       static/css/accessibility-fixes.css

# Shim base template that just forwards to the new one.
remove gigs/templates/gigs/base.html

# Old test_settings module (replaced by in-memory sqlite branch in settings.py).
remove quickgigs_project/test_settings.py

echo ""
echo "✓ Cleanup complete."
echo "Next steps:"
echo "  1) Inspect changes:  git status"
echo "  2) Stage everything: git add -A"
echo "  3) Commit:           git commit -m 'Modernize project structure & UI'"
echo ""
echo "Important: rotate your Stripe TEST keys in the Stripe dashboard."
echo "They are still in git history (they were committed in .env)."
